---
title: "R Notebook"
output: html_notebook
---
 
```{r}
############## LIBRARIES =========================
library(readr) #for reading csv files
library(lubridate) #for working with dates
library(chron) #for working with times

library(scales) # for working with date/time in plots
library(ggplot2) # for plots

library(dplyr)

```
 
```{r}
############## CREATE DATAFRAMES  =========================

#Rilka
dat.rilka <-
    read_csv("../../dat/Rilka_20190713_20200313.csv") %>%  #read raw file
    rename (date_time = 'Date and Time') %>% #convert character dates to usable date object  
    rename (Extra = 'Extra data') %>% # convert column name to a friendlier format with no spaces
    rename (Duration = 'Duration (min)')%>% # same as above
    mutate (ID = "Rilka") 

#Amos
dat.amos<-
    read_csv("../../dat/Amos_20190713_20200313.csv") %>%  #read raw file
    rename (date_time = 'Date and Time') %>% #convert character dates to usable date object  
    rename (Extra = 'Extra data') %>% # convert column name to a friendlier format with no spaces
    rename (Duration = 'Duration (min)')%>% # same as above
    mutate (ID = "Amos") 


```
 
```{r}
############## CALCULATE TOTALS =========================

#------------------
# TOTAL NURSING
#------------------
#RILKA
nursing.r<- 
    dat.rilka %>%
    filter(Activity=="Nursing") %>%
    select(Duration) %>% 
    rename(nursing='Duration') %>%
    summarise_all(funs(sum))*12  #assume 60ml in 5 minutes, 12mL/min 
    
 
#AMOS
nursing.a<- 
    dat.amos %>%
    filter(Activity=="Nursing") %>%
    select(Duration) %>%
    rename(nursing='Duration') %>%
    summarise_all(funs(sum))*12  #assume 60ml in 5 minutes, 12mL/min 
    

#------------------
# TOTAL FORMULA
#------------------

#RILKA
formula.r<- 
    dat.rilka %>%
    filter(Activity=="Bottle") %>%
    filter(Extra=="Formula") %>%
    select(Quantity) %>%
    summarise_all(funs(sum))%>%
    rename(formula=Quantity)

#AMOS
formula.a<- 
    dat.amos%>%
    filter(Activity=="Bottle") %>%
    filter(Extra=="Formula") %>%
    select(Quantity) %>%
    summarise_all(funs(sum))%>%
    rename(formula=Quantity)


#------------------
# TOTAL PUMPED MILK
#------------------
 
#RILKA
pumped.r<- 
    dat.rilka %>%
    filter(Activity=="Bottle") %>%
    filter(Extra=="Milk" | Extra == "Leche") %>%
    select(Quantity) %>%
    summarise_all(funs(sum))%>%
    rename(pumped=Quantity)

#AMOS
pumped.a<- 
    dat.amos %>%
    filter(Activity=="Bottle") %>%
    filter(Extra=="Milk" | Extra == "Leche") %>%
    select(Quantity) %>%
    summarise_all(funs(sum)) %>%
    rename(pumped=Quantity)

#------------------
# GRAND TOTAL
#------------------

total.r<-
    Reduce(function(x,y) merge(x,y,all=TRUE) ,list(pumped.r,formula.r,nursing.r)) %>% 
    mutate(total = rowSums(.)) %>%
    mutate(calories= pumped + nursing + formula*0.7) %>%
    mutate(ID="Rilka")
  

total.a<-
    Reduce(function(x,y) merge(x,y,all=TRUE) ,list(pumped.a,formula.a,nursing.a)) %>% 
    mutate(total = rowSums(.)) %>%
    mutate(calories= pumped + nursing + formula*0.7) %>%
    mutate(ID="Amos")

  

```
 
 