---
title: "R Notebook for initial analysis of 6 month Amos and Rilka"
output: html_notebook
---
 
```{r}
############## LIBRARIES =========================
library(readr) #for reading csv files
library(lubridate) #for working with dates
library(chron) #for working with times

library(scales) # for working with date/time in plots
library(ggplot2) # for plots

library(dplyr)

```
 
 
```{r}
############## LOAD FILES and CREATE DATAFRAME, with age and location ========================

# Load csv files
dat.amos <-
    read_csv("../../dat/Amos_20190613_20200111.csv") %>%  #read raw file
    rename (date_time = 'Date and Time') %>%    #convert character dates to usable date object
    mutate (ID = "Amos")

dat.rilka <-
    read_csv("../../dat/Rilka_20190613_20200111.csv") %>%  #read raw file
    rename (date_time = 'Date and Time') %>% #convert character dates to usable date object  
    mutate (ID = "Rilka")

# Create a dataframe for both their data together
dat.merged <-
    merge(dat.amos,dat.rilka, all=TRUE) %>%
    mutate (y.m.d = as.POSIXct(
        substr(date_time,1,9), 
        format="%m/%d/%y")) %>% # convert character date and time columns
    mutate (hr.min = substr(date_time,8,15)) %>%        # create a time column 
    mutate(hr.min = as.POSIXct(dat.merged$hr.min, format = "%H:%M")) #this inserts a placeholder 'date' that can be ignored

 
 
# Add age columns 
BIRTHDATE <- as.POSIXct("2019-07-13")
dat.merged <-
    dat.merged %>%
    mutate(age.days = difftime( #age in days, starting at zero 
        as.POSIXct(y.m.d), BIRTHDATE, 
        units="days")) %>%
    mutate(age.days = round(age.days,0)) %>%  
    mutate(age.wks = difftime ( #age in days, starting at zero
        as.POSIXct(y.m.d), BIRTHDATE,
        unit = "weeks")) %>%
    mutate(age.wks = round(age.wks,1))


 

    


# Add location tags
dat.merged$locID <-
    case_when(
            dat.merged$y.m.d %within% interval(ymd("2019-07-13"),ymd("2019-09-02")) ~ "Toronto",
            dat.merged$y.m.d %within% interval(ymd("2019-09-02"),ymd("2019-10-01")) ~ "Caribou River",
            dat.merged$y.m.d %within% interval(ymd("2019-10-01"),ymd("2019-11-30")) ~ "Paris",
            dat.merged$y.m.d %within% interval(ymd("2019-11-30"),ymd("2019-12-29")) ~ "Villemus",
            dat.merged$y.m.d %within% interval(ymd("2019-12-29"),ymd("2020-01-20")) ~ "Nice",
            TRUE ~ "unspecified") 

# Factorize
dat.merged <-
    dat.merged %>%
    mutate_at(vars(Activity,Caregiver,ID,locID),factor)


```
 
```{r}
############## VIZUALIZE SOME DATA :) ========================

dat.subset <-
    dat.merged %>%
    select (-c('End Time',date_time,Notes)) 


# plot Overview histogram of data entered
ggplot(dat.subset, aes(hr.min, fill = Activity)) +
  geom_histogram(binwidth = 500)


# plot concentration of eating times, e.g., activity == bottle and hr.min
dat.subset %>%
    filter(Activity=="Bottle") %>%
    ggplot(aes(x=hr.min,fill=Activity)) +
        geom_histogram(binwidth = 1000) +
        stat_count(position="identity") +
        scale_x_time(breaks = "0.5 hours") +
        labs(x="Time of day", y="count\n")  

 

#plot hours slept in each city
dat.subset%>%
    filter(Activity=="Sleep") %>%
    ggplot(aes(x= 'ID',fill=locID)) +
        geom_bar(position="stack") + 
        facet_grid(.~ID) +
        theme_minimal() +
        labs(x="Minutes slept in each City", y="[minutes]\n") + 
        theme(panel.grid.major=element_blank()) 
 

dat.subset %>%
    filter(Activity=="Sleep")%>%
    #aggregate(Activity ~ locID, FUN = sum) %>%
    ggplot(aes(x=locID, y= Activity)) +
        geom_bar(stat = "identity")
 

# plot Quantity if Activity == head size


```
 
 